version: 0.1.2-build{build}
skip_non_tags: true
os: Windows Server 2012 R2
shallow_clone: true

branches:
  only:
  - master
  - /v\d\.\d\.\d/

configuration: Release

environment:
  qtcryptohash_version: 0.1.2
  qt_version: 5.6
  msvc_dir: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
  mingw_dir: C:\Qt\Tools\mingw492_32\bin
  
  matrix:
  #MSVC x86
  - name: msvc2015-win32
    arch: x86
    compiler: msvc
    type: dynamic
    qt_dir: C:\Qt\%qt_version%\msvc2015\bin
    
  #MSVC x86 STATIC
  - name: msvc2015-win32-static
    arch: x86
    compiler: msvc
    type: static
    qt_dir: C:\Qt\%qt_version%\msvc2015\bin
    
  #MSVC x64
  - name: msvc2015-win64
    arch: x64
    compiler: msvc
    type: dynamic
    qt_dir: C:\Qt\%qt_version%\msvc2015_64\bin
    
  #MSVC x64 STATIC
  - name: msvc2015-win64-static
    arch: x64
    compiler: msvc
    type: static
    qt_dir: C:\Qt\%qt_version%\msvc2015_64\bin
    
  #MinGW x86
  - name: mingw49-win32
    arch: x86
    compiler: mingw
    type: dynamic
    qt_dir: C:\Qt\%qt_version%\mingw49_32\bin
    
  #MinGW x86 STATIC
  - name: mingw49-win32-static
    arch: x86
    compiler: mingw
    type: static
    qt_dir: C:\Qt\%qt_version%\mingw49_32\bin

init:
    - set PATH=%PATH%;%msvc_dir%;%mingw_dir%;%qt_dir%
    - if [%compiler%]==[msvc]
        call vcvarsall.bat %arch%

build_script:
    - mkdir build
    - cd build
    - if [%type%]==[static] (
        qmake ..\QtCryptoHash.pro "CONFIG += static"
      ) else (
        qmake ..\QtCryptoHash.pro
      )
    - if [%compiler%]==[msvc] ( 
        nmake debug & nmake release
      ) else (
        mingw32-make debug & mingw32-make release
      )
    - cd ..
    - mkdir pkg
    - cd pkg
    - mkdir bin\%arch%\debug\
    - mkdir bin\%arch%\release\
    - if [%compiler%]==[msvc] (
        copy /y ..\bin\%arch%\%type%\debug\*.lib bin\%arch%\debug\ &
        copy /y ..\bin\%arch%\%type%\release\*.lib bin\%arch%\release\
      ) else (
        copy /y ..\bin\%arch%\%type%\debug\*.a bin\%arch%\debug\ &
        copy /y ..\bin\%arch%\%type%\release\*.a bin\%arch%\release\  
      )
    - if [%type%]==[dynamic] (
        copy /y ..\bin\%arch%\%type%\debug\*.dll bin\%arch%\debug\ &
        copy /y ..\bin\%arch%\%type%\release\*.dll bin\%arch%\release\
      )
    - copy /y ..\lib\include\qcryptohash.hpp qcryptohash.hpp
    - 7z a -t7z QtCryptoHash-v%qtcryptohash_version%-%name%.7z *
    
artifacts:
    - path: pkg\**\*.7z
      name: binary

test: off

deploy:
    provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Binaries of QtCryptoHash $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: 4V5xJQT+iVPUhK05TBLkNkLY8HTArZ+omH394hfXqQuxfrkaQqnR8132rDnB/HVm
    artifact: /.*\.7z/
    draft: true
    prerelease: false
    on:
      # branch: master
      appveyor_repo_tag: true