version: 0.1.1-build{build}
skip_non_tags: true
os: Windows Server 2012 R2
shallow_clone: true

branches:
  only:
  - master

configuration: Release

environment:
  qtcryptohash_version: 0.1.1
  qt_version: 5.5
  msvc_dir: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC
  mingw_dir: C:\Qt\Tools\mingw492_32\bin
  
  matrix:
  #MSVC x86
  - name: msvc2013-win32
    arch: x86
    compiler: msvc
    type: dynamic
    target: QtCryptoHash.dll
    qt_dir: C:\Qt\%qt_version%\msvc2013\bin
    
  #MSVC x86 STATIC
  - name: msvc2013-win32-static
    arch: x86
    compiler: msvc
    type: static
    target: QtCryptoHash.lib
    qt_dir: C:\Qt\%qt_version%\msvc2013\bin
    
  #MSVC x64
  - name: msvc2013-win64
    arch: x64
    compiler: msvc
    type: dynamic
    target: QtCryptoHash64.dll
    qt_dir: C:\Qt\%qt_version%\msvc2013_64\bin
    
  #MSVC x64 STATIC
  - name: msvc2013-win64-static
    arch: x64
    compiler: msvc
    type: static
    target: QtCryptoHash64.lib
    qt_dir: C:\Qt\%qt_version%\msvc2013_64\bin
    
  #MinGW x86
  - name: mingw49-win32
    arch: x86
    compiler: mingw
    type: dynamic
    target: QtCryptoHash.dll
    qt_dir: C:\Qt\%qt_version%\mingw492_32\bin
    
  #MinGW x86 STATIC
  - name: mingw49-win32-static
    arch: x86
    compiler: mingw
    type: static
    target: libQtCryptoHash.a
    qt_dir: C:\Qt\%qt_version%\mingw492_32\bin

init:
    - set PATH=%PATH%;%msvc_dir%;%mingw_dir%;%qt_dir%
    - if [%compiler%]==[msvc]
        call vcvarsall.bat %arch%

build_script:
    - mkdir build
    - cd build
    - if [%type%]==[static] (
        qmake ..\QtCryptoHash.pro "CONFIG += static"
      ) else (
        qmake ..\QtCryptoHash.pro
      )
    - if [%compiler%]==[msvc] ( 
        nmake debug & nmake release
      ) else (
        mingw32-make debug & mingw32-make release
      )
    - cd ..
    - mkdir pkg
    - cd pkg
    - mkdir bin\%arch%\debug\
    - mkdir bin\%arch%\release\
    - copy /y ..\bin\%arch%\%type%\debug\%target% bin\%arch%\debug\%target%
    - copy /y ..\bin\%arch%\%type%\release\%target% bin\%arch%\release\%target%
    - copy /y ..\lib\include\qcryptohash.hpp qcryptohash.hpp
    - 7z a -t7z QtCryptoHash-v%qtcryptohash_version%-%name%.7z *
    
artifacts:
    - path: pkg\**\*.7z
      name: binary

test: off

deploy:
    provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Binaries of QtCryptoHash v%qtcryptohash_version%'
    auth_token:
      secure: 4V5xJQT+iVPUhK05TBLkNkLY8HTArZ+omH394hfXqQuxfrkaQqnR8132rDnB/HVm
    artifact: /.*\.7z/
    draft: true
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true